# Build settings
permalink: /blog/:categories/:title/
markdown: kramdown
highlighter: Rouge
plugins: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

incremental: true
live_reload: true
host: 0.0.0.0

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Psico Daniela Lins
description: "Here you can find some personal information, resume and blog from Matheus Costa Vieira"
keywords: "Jekyll, personal information, resume, Matheus, Costa, Vieira, Matheus Costa Vieira, blog"
url: http://daniplins.github.io
baseurl: ""

google_analytics: UA-174941014-1
site.google_analytics_container: GTM-TWNMZ5Q
repo: https://github.com/daniplins/daniplins.github.io
disqus_shortname: ""
disqus_site_shortname: ""

# Compress
compress_html:
  clippings: []
  comments: []
  endings: []
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []

# Author settings
author:
  name: Daniela Priscila Lins
  job: Psicóloga Comportamental
  bio: "Psicóloga com foco em crianças e adolescentes em idade escolar."
  thumb: /images/author.png
  logo: /images/logo.png
  email: daniplins@gmail.com
  url: http://daniplins.github.io
  github: https://github.com/daniplins
  twitter: https://twitter.com/PDanielalins
  facebook: https://facebook.com/psico.danielalins
  linkedin: https://linkedin.com/in/daniela-priscila-lins-095491204
  instagram: https://instagram.com/psico.danielalins
  whatsapp: https://api.whatsapp.com/send?phone=5541987237281&text=Podemos conversar?
  phone: "5541987237281"
  cellphone: "+55 41 9 87237281"

max_experiences: 4

messages:
  pt-br:
    page-title: Currículo
    print-alert: "Opcionalmente remova o cabeçalho nas opções de impressão"
    print-resume:
      location: "Curitiba- Paraná - Brasil"
      title:
        goal: "Objetivo"
        education: "Formação Acadêmica"
        courses: "Cursos"
        experiences: "Experiência"
        institution: "Instituição"
        skills: "Conhecimentos"
        course: "Curso"
        company: "Empresa"
        current: "Atual"
        skills-idiom: "Idiomas"
        skills-languages: "Linguagens"
        skills-framework: "Frameworks"
        skills-others: "Outras"
      goal: "Criar novos e melhores conceitos usando padrões de design e melhores práticas para o desenvolvimento de aplicativos.<br />
       Fazendo uso de testes automatizados para garantir a qualidade do sistema.<br />
       Tendo em mente a resolução do problema com a melhor experiência para o usuário."
  en-us:
    page-title: Resume
    print-alert: "Optionally remove header in print options"
    print-resume:
      location: "Curitiba- Paraná - Brazil"
      title:
        goal: "Goal"
        education: "Academic formation"
        courses: "Courses"
        experiences: "Experiences"
        institution: "Institution"
        skills: "Skills"
        course: "Course"
        company: "Company"
        current: "Actual"
        skills-idiom: "Speak"
        skills-languages: "Languages"
        skills-framework: "Frameworks"
        skills-others: "Others"
      goal: "Create new and better concepts using design patterns and best practices for the development of applications.<br />
       Making use of automated tests to ensure the system quality.<br />
       Keeping on mind the problem resolution with the best experience for the user."

# navbar pages
navbar:
  - slug: sobre
    title: Sobre
  - slug: contato
    title: Contato

collections:
 - graduations
 - experiences
 - skills

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
