# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

incremental: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: mvieira
description: "An site with some personal informations, resume and blog from Matheus Costa Vieira"
keywords: "Jekyll, personal information, resume, Matheus, Costa, Vieira, Matheus Costa Vieira, blog, w"
url: http://matheus-vieira.github.io
baseurl: ""

google_analytics: UA-27171689-1
repo: https://github.com/matheus-vieira/matheus-vieira.github.io
disqus_shortname: "matheuscostavieira"
disqus_site_shortname: "matheuscostavieira"

# Author settings
author:
  name: Matheus Costa Vieira
  job: Software Engineer
  bio: "I love God, my wife, my son and my little daughter (an angel) and then I love to create programs!"
  thumb: /images/author.png
  email: matheus.costa.vieira@gmail.com
  email-prof : matheus.vieira@opet.edu.br
  url: http://matheus-vieira.github.io
  github: https://github.com/matheus-vieira
  twitter: https://twitter.com/macostavieira
  facebook: https://facebook.com/macovieira
  linkedin: https://linkedin.com/in/macostavieira
  gplus: https://plus.google.com/+MatheusCostaVieira
  instagram: https://instagram.com/matheuscostavieira
  whatsapp: https://api.whatsapp.com/send?phone=5541988024599&text=E ae!
  phone: "5541988024599"

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: resume
    title: Resume
  - slug: blog
    title: Blog
  - slug: courses
    title: Courses
  - slug: contact
    title: Contact

collections:
 - graduations
 - experiences

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
